server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flametalk_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: flame
    password: flame123!@#

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.format_sql: true

security:
  oauth2:
    jwt:
      signkey: 123@#$